### ISSUE TITLE
R crashes when using virtual environment  : scircm

### ISSUE THREAD

**Issue by Nade-zh** [ArianeMora/scircm#1]
Hi Ariane, 
I am trying to use the script in Mac, I have followed the instructions but when I want to use the virtual environment R studio crashes. I have installed Phyton, Rtools and all required packages. 

Thanks for your help 

# install.packages("reticulate), Create a new environment and install scircm.

virtualenv_create(
      envname = "ml",
      python = NULL,
      packages = "scircm",
      system_site_packages = getOption("reticulate.virtualenv.system_site_packages",
                                       default = FALSE))
```
## Install the R package

```{r}
#install.packages("devtools")
library(devtools)
#install_github("ArianeMora/SiRCleR")
library(sircle)
```

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(reticulate)
library(readxl)

use_virtualenv("ml", required = TRUE)
scirm<<-import("scircm")
```
**-------> HERE IT CRASHES** 
```{r}
prot_file <- read.csv ("Data/AffectedvsWT_prot.csv")
rna_file  <- read.csv ("Data/AffectedvsWT_RNA.csv")
meth_file <- read.csv ("Data/AffectedvsWT_meth.csv")

**Comment by ArianeMora** [comment]
Hi! What version of R and python are you running? Python needs to be > 3.8. If you have a mac you can go to terminal and type: `python --version`
If your python version is < 3.8 you might have issues, if so I would recommend using conda to create virtual environments, to do this: 
1) Install miniconda (https://docs.conda.io/en/latest/miniconda.html)
2) Once it is installed, go to your terminal and type: `conda create --name ml python=3.8` then select `y`. 
3) After it has finished creating type into your terminal: `conda activate ml`
4) Finally run: `pip install scircm`
You'll only need to do this once :) 

Now in R instead of this line: 
`use_virtualenv("ml", required = TRUE)`
use this line:
`use_condaenv('ml', required = TRUE)`

Let me know if this works! If not, can you please send the error message? Then I'll be able to help more with any issues :)

**Comment by Nade-zh** [comment]
Dear Ariane, 
Thanks for your reply. 

My  Phyton version is  3.9.12, and R version 4.1.2

I have done what you suggested, all runs smoothly until I try to install scircm. Here the Errors. 

------------------

Collecting scircm
  Using cached scircm-1.0.0-py3-none-any.whl (37 kB)
**ERROR: Cannot install scircm because these package versions have conflicting dependencies.**

The conflict is caused by:
    scivae 1.0.8 depends on tensorflow>=2.9
    scivae 1.0.6 depends on tensorflow
    scivae 1.0.5 depends on tensorflow
    scivae 1.0.4 depends on tensorflow
    scivae 1.0.3 depends on tensorflow
    scivae 1.0.2 depends on tensorflow
    scivae 1.0.1 depends on tensorflow
    scivae 1.0.0 depends on tensorflow

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts**
-----------

I tried to remove the package version on the 1st command, but it came the same error. 

Thanks!!

**Comment by Nade-zh** [comment]
Dear Ariane, 

Thanks for your reply. I have done the steps you suggested and all runs smoothly until I go back to R studio. 

My R version is 4.12/ Phyton 3.9 

<img width="916" alt="Captura de Pantalla 2022-08-15 a la(s) 11 38 05" src="https://user-images.githubusercontent.com/78903908/184612779-4c025c2e-5a9d-4571-802c-d643248009d8.png">

THEN... 

```{r}
library(tidyverse)
library(dplyr)
library(reticulate)
library(readxl)
use_condaenv('ml', required = TRUE)
Until here it runs fine....

**In this command line the Rstudio  session is ABORTED**

scircm <- import("scircm")

```

I cannot show you any error.... after that Rstudio  restarts

Thanks

**Comment by Nade-zh** [comment]
<img width="829" alt="Captura de Pantalla 2022-08-15 a la(s) 14 16 31" src="https://user-images.githubusercontent.com/78903908/184633635-09aca76f-7752-46dc-b267-a155ddd40580.png">

**Comment by ArianeMora** [comment]
Hi Nade, thanks for following those instructions, sorry it doesn't work still! I'm currently at a conference for this week but I will try and recreate the error next week as soon as I'm home :) One last question, do you have one of the latest macs with an M1 chip? I know those sometimes have issues with tensorflow...

**Comment by ArianeMora** [comment]
Hi Nade, I tested the package on my colleagues laptop who has a mac with an M1 chip and he had the same issue. There are issues with using the machine learning package I use (tensorflow) on Macs, I'm not sure what a workaround for this is, but perhaps we'll look into making a web version. Will let you know if we get a version you can use :)

**Comment by Nade-zh** [comment]
Hi Ariane, 

Thanks! Is it possible to do it on a Mac without M1 chip? Or this has just to do with Mac system. 
Perhaps, I can try in the meantime to borrow a laptop. 

Thanks for your help :) 

Nadezh

**Comment by ArianeMora** [comment]
Hi Nadezh, no issues on a normal mac (I have a mac :) just not the new one!) 
I tried a number of things on my colleagues computer and haven't gotten it to work on the M1 chip but you may have more luck, this tutorial looks like it may work: https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb If you do succeed let me know and I'll add some installation instructions.

Also as an aside, which part of SiRCle were you wanting to do? I could re-build the first part of the package for you (the regulatory clustering) because that doesn't rely on tensorflow so should work on a M1 Mac :)

**Comment by Nade-zh** [comment]
Hi Ariane, 
I have tried several options on the M1, no success until now. Tough thanks for the support. Yes, I want to run the regulatory clustering, the first part. 
Thanks again!

Nadezh

**Comment by ArianeMora** [comment]
Hi Nadezh, OK so I've made you a new version for the mac M1 chip :) https://github.com/ArianeMora/SiRCleR_M1 the instructions are on that github and hopefully everything runs smooth! I did test it on my colleagues mac with the M1 and it all worked well :D Please let me know if you have any issues and thank you for bearing with us while we sorted out the M1 issues!
